version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:1000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
